# Generated by Django 2.2.24 on 2021-06-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='passwd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='introduction',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='access',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='contents',
            field=models.TextField(max_length=100),
        ),
    ]
