# Generated by Django 2.2.24 on 2021-06-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210630_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='passwd',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
