# Generated by Django 2.2.24 on 2021-06-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210630_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
