# Generated by Django 2.2.24 on 2021-07-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210630_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'ordering': ['-number']},
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='version',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='passwd',
        ),
    ]
