# Generated by Django 2.2.24 on 2021-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210701_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='access',
            new_name='writer',
        ),
    ]
