# Generated by Django 2.2.24 on 2021-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('ALL', '전체'), ('VG', '비건'), ('LO', '락토-오보'), ('PC', '페스코'), ('PL', '폴로'), ('FT', '플렉시테리언')], default='FT', max_length=6)),
            ],
        ),
    ]
