# Generated by Django 2.2.24 on 2021-06-30 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('begin_vegan', '0006_post_user'),
        ('accounts', '0002_auto_20210630_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
